easy_admin:
    site_name: 'ELBASE Back Office'
    entities:
        # List the entity class name you want to manage
        User:
            class: App\Entity\User
        Todo:
            class: App\Entity\Todo
        Account:
            class: App\Entity\Account
        OperationPlus:
            class: App\Entity\OperationPlus
        OperationMinus:
            class: App\Entity\OperationMinus
