framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: ~
    #http_method_override: true

    session:
        handler_id: ~
        save_path: "%kernel.root_dir%/test/sessions"
        name: ELBASE_PHPSESSID

    #esi: ~
    #fragments: ~
    php_errors:
        log: true
