security:
    providers:
        maindb:
          entity:
              class: App\Entity\User
              property: username
        in_memory:
          memory:
              users:
                  elie:
                      password: elie
                      roles: 'ROLE_USER'
                  admin:
                      password: admin
                      roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: in_memory
            form_login:
              login_path: login
              check_path: login
              default_target_path: dashboard
            logout:
              path:   /logout
              target: /

    access_control:
         - { path: ^/dashboard, roles: ['ROLE_USER','ROLE_ADMIN'] }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        App\Entity\User:
            algorithm: bcrypt