security:
    providers:
          maindb:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: maindb
            form_login:
              login_path: login
              check_path: login
            logout:
              path:   /logout
              target: /

    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/dashboard, roles: ['ROLE_USER','ROLE_ADMIN'] }

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12