<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMFOj17i\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMFOj17i/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMFOj17i.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMFOj17i\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMFOj17i\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'MFOj17i',
    'container.build_id' => 'c3659fc0',
    'container.build_time' => 1520433134,
));
