<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN7w3Cj5\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN7w3Cj5/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerN7w3Cj5.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerN7w3Cj5\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerN7w3Cj5\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'N7w3Cj5',
    'container.build_id' => '7e2d89cf',
    'container.build_time' => 1520258615,
));
